version: 2

sources:
    - name: jaffle_shop_raw
      database: jaffle_shop
      schema: jaffle_shop_raw
      tables:
        - name: raw_customers
        - name: raw_orders
        - name: raw_products
        - name: raw_items
        - name: raw_stores
        - name: raw_supplies