jaffle_shop:
  outputs:
    dev:
      dbname: jaffle_shop
      host: 127.0.0.1
      pass: postgres
      port: 5433
      schema: gold
      threads: 1
      type: postgres
      user: postgres
  target: dev