jaffle_shop:
  outputs:
    dev:
      dbname: jaffle_shop
      host: host.docker.internal
      pass: postgres
      port: 5433
      schema: jaffle_shop
      threads: 1
      type: postgres
      user: postgres
  target: dev